### ISSUE TITLE
DeadLock Error 

### ISSUE THREAD

**Issue by owen-jia** [owen-jia/lts-parent#11]
出现大量error日志，同时期出现大量warn日志，在代码的一块区域出现，两种存在必然关系。

code：
`    private List<JobPo> fetchJob(String taskTrackerNodeGroup, String taskTrackerIdentity, int size) {
        List<JobPo> jobPos = new ArrayList<JobPo>(size);

        for (int i = 0; i < size; i++) {
            // 从mongo 中取一个可运行的job
            final JobPo jobPo = appContext.getPreLoader().take(taskTrackerNodeGroup, taskTrackerIdentity);
            if (jobPo == null) {
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("Job push failed: no job! nodeGroup=" + taskTrackerNodeGroup + ", identity=" + taskTrackerIdentity);
                }
                break;
            }

            // IMPORTANT: 这里要先切换队列
            try {
                appContext.getExecutingJobQueue().add(jobPo);
            } catch (DupEntryException e) {
                LOGGER.warn("ExecutingJobQueue already exist:" + JSON.toJSONString(jobPo));
                appContext.getExecutableJobQueue().resume(jobPo);
                continue;
            }
            appContext.getExecutableJobQueue().remove(jobPo.getTaskTrackerNodeGroup(), jobPo.getJobId());

            jobPos.add(jobPo);
        }
        return jobPos;
    }`

`    public JobPo take(String taskTrackerNodeGroup, String taskTrackerIdentity) {
        while (true) {
            JobPo jobPo = get(taskTrackerNodeGroup);
            if (jobPo == null) {
                DotLogUtils.dot("Empty JobQueue, taskTrackerNodeGroup:{}, taskTrackerIdentity:{}", taskTrackerNodeGroup, taskTrackerIdentity);
                return null;
            }
            // update jobPo
            PeriodUtils.start();
            try {
                if (lockJob(taskTrackerNodeGroup, jobPo.getJobId(),
                        taskTrackerIdentity, jobPo.getTriggerTime(),
                        jobPo.getGmtModified())) {
                    jobPo.setTaskTrackerIdentity(taskTrackerIdentity);
                    jobPo.setIsRunning(true);
                    jobPo.setGmtModified(SystemClock.now());
                    return jobPo;
                }
            } finally {
                PeriodUtils.end("AbstractPreLoader.lockJob taskId:{}", jobPo.getTaskId());
            }
        }
    }`

log：
`[lts] 2020-03-10 05:16:14,093 ERROR [AbstractServerNode-thread-23] com.github.ltsopensource.core.logger.slf4j.Slf4jLogger.error(76) |  [LTS] Error when lock job:Update SQL Error:
    UPDATE
        `lts_wjq_rentTaskTracker`  
    SET
        `is_running` = ? ,
        `task_tracker_identity` = ? ,
        `gmt_modified` = ?  
    WHERE
        job_id = ? 
        AND is_running = ? 
        AND trigger_time = ? 
        AND gmt_modified = ?, lts version: 1.7.0, current host: 10.10.63.225
com.github.ltsopensource.store.jdbc.exception.JdbcException: Update SQL Error:
    UPDATE
        `lts_wjq_rentTaskTracker`  
    SET
        `is_running` = ? ,
        `task_tracker_identity` = ? ,
        `gmt_modified` = ?  
    WHERE
        job_id = ? 
        AND is_running = ? 
        AND trigger_time = ? 
        AND gmt_modified = ?
	at com.github.ltsopensource.store.jdbc.builder.UpdateSql.doUpdate(UpdateSql.java:182)
	at com.github.ltsopensource.queue.mysql.MysqlPreLoader.lockJob(MysqlPreLoader.java:60)
	at com.github.ltsopensource.queue.AbstractPreLoader.take(AbstractPreLoader.java:150)
	at com.github.ltsopensource.jobtracker.sender.JobSender.fetchJob(JobSender.java:61)
	at com.github.ltsopensource.jobtracker.sender.JobSender.send(JobSender.java:33)
	at com.github.ltsopensource.jobtracker.complete.biz.PushNewJobBiz.getNewJob(PushNewJobBiz.java:47)
	at com.github.ltsopensource.jobtracker.complete.biz.PushNewJobBiz.doBiz(PushNewJobBiz.java:33)
	at com.github.ltsopensource.jobtracker.processor.JobCompletedProcessor.processRequest(JobCompletedProcessor.java:42)
	at com.github.ltsopensource.jobtracker.processor.RemotingDispatcher.doBiz(RemotingDispatcher.java:80)
	at com.github.ltsopensource.jobtracker.processor.RemotingDispatcher.processRequest(RemotingDispatcher.java:57)
	at com.github.ltsopensource.remoting.AbstractRemoting$1.run(AbstractRemoting.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Deadlock found when trying to get lock; try restarting transaction Query: UPDATE  `lts_wjq_rentTaskTracker`  SET `is_running` = ? ,`task_tracker_identity` = ? ,`gmt_modified` = ?  WHERE job_id = ? AND is_running = ? AND trigger_time = ? AND gmt_modified = ? Parameters: [true, TT_10.10.103.12_3620_13-32-53.502_2, 1583788574088, 387461ABB8DF40DBA4AEFE9BBC99868F, false, 1583788573998, 1583788573998]
	at com.github.ltsopensource.store.jdbc.dbutils.DbRunner.rethrow(DbRunner.java:232)
	at com.github.ltsopensource.store.jdbc.dbutils.DbRunner.update(DbRunner.java:84)
	at com.github.ltsopensource.store.jdbc.dbutils.DbRunner.update(DbRunner.java:60)
	at com.github.ltsopensource.store.jdbc.SqlTemplateImpl.update(SqlTemplateImpl.java:87)
	at com.github.ltsopensource.store.jdbc.SqlTemplateImpl$2.run(SqlTemplateImpl.java:76)
	at com.github.ltsopensource.store.jdbc.SqlTemplateImpl$2.run(SqlTemplateImpl.java:73)
	at com.github.ltsopensource.store.jdbc.SqlTemplateImpl.execute(SqlTemplateImpl.java:30)
	at com.github.ltsopensource.store.jdbc.SqlTemplateImpl.update(SqlTemplateImpl.java:73)
	at com.github.ltsopensource.store.jdbc.builder.UpdateSql.doUpdate(UpdateSql.java:180)
	... 15 more`

`[lts] 2020-03-09 02:30:20,981 WARN [AbstractServerNode-thread-5] com.github.ltsopensource.core.logger.slf4j.Slf4jLogger.warn(56) |  [LTS] ExecutingJobQueue already exist:{"cron":false,"extParams":{"date":"2020-03-09","ifMerge":"N","contractId":"798","customerId":"125","type":"contract","nodeId":"b67d7cd3b5d04ccb864718c0632c0db2"},"gmtCreated":1583692219264,"gmtModified":1583692220978,"internalExtParams":{"__LTS_Seq_Id":"1583692219264"},"jobId":"811CD55A5492458C88EB51B0391B5FE3","jobType":"REAL_TIME","lastGenerateTriggerTime":0,"maxRetryTimes":3,"needFeedback":false,"priority":100,"realTaskId":"contract:b67d7cd3b5d04ccb864718c0632c0db2-125-2020-03-09-false","relyOnPrevCycle":true,"repeatCount":0,"repeatInterval":0,"repeatable":false,"repeatedCount":0,"retryTimes":0,"running":true,"submitNodeGroup":"rentJobClient","taskId":"contract:b67d7cd3b5d04ccb864718c0632c0db2-125-2020-03-09-false","taskTrackerIdentity":"TT_10.10.103.12_31065_14-25-32.613_2","taskTrackerNodeGroup":"rentTaskTracker","triggerTime":1583692219264}, lts version: 1.7.0, current host: 10.10.63.225`

**Comment by owen-jia** [comment]
version=1.7.0
